# Generated by Django 3.2.9 on 2021-12-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Interests',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('details', models.CharField(blank=True, max_length=45, null=True)),
                ('maxsize', models.IntegerField(blank=True, db_column='maxSize', null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tourcount', models.IntegerField(blank=True, db_column='tourCount', null=True)),
                ('guide', models.CharField(blank=True, max_length=45, null=True)),
                ('interests', models.ManyToManyField(to='buddyAbroadAPI.Interests')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidprice', models.FloatField(blank=True, db_column='paidPrice', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('groupsize', models.IntegerField(blank=True, db_column='groupSize', null=True)),
                ('user_tripscol', models.CharField(blank=True, max_length=45, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.trips')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tourist', to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'user_trips',
            },
        ),
        migrations.CreateModel(
            name='UsersLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.ForeignKey(db_column='Languages_id', on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.languages')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'users_languages',
            },
        ),
        migrations.AddField(
            model_name='trips',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users'),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='BuddyMatchTourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.CharField(blank=True, max_length=100, null=True)),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'buddy_match_tourist',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, db_column='recipient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users')),
                ('sender', models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'messages',
                'unique_together': {('sender', 'recipient')},
            },
        ),
    ]
