# Generated by Django 3.2.9 on 2022-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
