# Generated by Django 4.0.1 on 2022-02-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0002_rename_name_users_f_name_users_dob_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='f_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='interests',
            field=models.ManyToManyField(blank=True, to='buddyAbroadAPI.Interests'),
        ),
        migrations.AlterField(
            model_name='users',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='languages',
            field=models.ManyToManyField(blank=True, to='buddyAbroadAPI.Languages'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
