# Generated by Django 4.0.1 on 2022-02-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0003_alter_users_age_alter_users_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='l_name',
        ),
    ]
