# Generated by Django 4.0.1 on 2022-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0004_rename_f_name_users_name_remove_users_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
