# Generated by Django 4.0.1 on 2022-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0005_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
