# Generated by Django 4.0.1 on 2022-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0006_alter_trips_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='hello',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
