# Generated by Django 4.0.1 on 2022-03-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0007_trips_hello_alter_trips_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='hello',
        ),
    ]
