# Generated by Django 4.0.1 on 2022-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0008_remove_trips_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'InterestCategories',
            },
        ),
    ]
