# Generated by Django 4.0.1 on 2022-04-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0009_interestcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buddyAbroadAPI.interestcategories'),
            preserve_default=False,
        ),
    ]
