# Generated by Django 4.0.1 on 2022-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0011_alter_users_email_alter_users_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
