# Generated by Django 4.0.1 on 2022-04-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0013_alter_users_email_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrips',
            name='user_tripscol',
        ),
    ]
