# Generated by Django 4.0.5 on 2022-06-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.trips')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to='buddyAbroadAPI.users')),
            ],
            options={
                'db_table': 'favourites',
            },
        ),
    ]
